const SUPABASE_URL = 'https://lrocighnjtundvcxvhar.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxyb2NpZ2huanR1bmR2Y3h2aGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcwMzk0MTQsImV4cCI6MjEwMjYxNTQxNH0.w8fmLmbs6M4HMUG5e--eSpNynLs3BDSvwT8ZIZR9i50';
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
